add python/whatsapp_with_vonage
appwrite/templates pull request #213
Opened 2023-10-02 20:14 UTC by probablyArth

## What does this PR do?

Added `python/whatsapp_with_vonage` function template.

## Test Plan

https://github.com/appwrite/templates/assets/61962871/cc021896-871a-414a-a478-bfd801691403

## Related PRs and Issues
closes #207 

### Have you read the [Contributing Guidelines on issues]

yes

2023-10-03 09:08 UTC, loks0n requested changes

2023-10-03 09:08 UTC, loks0n commented on python/whatsapp_with_vonage/src/main.py
> +            "VONAGE_SIGNATURE_SECRET",
Let's change the env var name here.

2023-10-03 09:08 UTC, loks0n commented on python/whatsapp_with_vonage/src/main.py
> +        auth=(environ["VONAGE_API_KEY"], environ["VONAGE_ACCOUNT_SECRET"]),
Let's change the env var name here.

2023-10-03 09:08 UTC, loks0n commented on python/whatsapp_with_vonage/src/main.py
> +        decode(token, environ["VONAGE_SIGNATURE_SECRET"], ["HS256"])
Let's change the env var name here.

2023-10-03 09:08 UTC, loks0n commented on python/whatsapp_with_vonage/src/main.py
> +from os import environ
Small nitpick: in other templates we've used just `import os` and `os.environ["ENVAR"]`
Can we match that?

2023-10-03 09:08 UTC, loks0n commented on python/whatsapp_with_vonage/src/main.py
> +    if context.req.method == "GET":
Can we add an empty line here

2023-10-03 12:28 UTC, probablyArth commented
Also, please add the hacktoberfest-accpeted label on the pr, currently it says that my PR is not participating in hacktoberfest.

2023-10-03 15:20 UTC, Meldiron commented on python/whatsapp_with_vonage/src/main.py
> +        return context.res.json({"ok": False, "error": "Invalid token!"}, 403)
I would recommend error message to be `Payload hash mismatch`, just like in Node version.

2023-10-03 15:21 UTC, Meldiron commented on python/whatsapp_with_vonage/src/main.py
> +    except ValueError as e:
Might be worth excepting everything

2023-10-03 15:22 UTC, Meldiron commented on python/whatsapp_with_vonage/src/main.py
> +        "text": f'you sent: {body["text"]}',
Suggesting text to be be:

```js
text: `Hi there! You sent me: ${req.body.text}`,
```

In order to be consistent with Node version

2023-10-03 15:23 UTC, Meldiron commented on python/whatsapp_with_vonage/src/main.py
> +        context.log(result)
Let's remove this log

2023-10-03 15:24 UTC, Meldiron requested changes
Let's please address my suggestions.

2023-10-04 09:30 UTC, loks0n approved these changes

2023-10-04 15:15 UTC, merged

2024-04-08 20:21 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-09 02:51 UTC, probablyArth commented
probablyarth