feat: sync with `meilisearch` for ruby
appwrite/templates pull request #233
Opened 2023-10-10 18:40 UTC by afzal442

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2023-10-13 10:20 UTC, loks0n requested changes
Thanks for the PR!

I've added some comments for you to address

2023-10-13 10:20 UTC, loks0n commented on ruby/meilisearch/config.rb
Can we just use ENV['FOO'] directly? We want to keep it consistent with the other templates and I don't think the pattern here provides enough benefit in this case

2023-10-13 10:20 UTC, loks0n commented on ruby/meilisearch/Gemfile
Can we have the template in `ruby/sync_with_meilisearch`?

2023-10-13 10:20 UTC, loks0n commented on ruby/meilisearch/lib/utils.rb
None of these functions are used!

Can we use them to match the behaviour of the node runtime

2023-10-13 10:20 UTC, loks0n commented on ruby/meilisearch/lib/main.rb
This file is not is the correct format.

To be a working appwrite function you need to define a `main` function that accepts a context and returns a response using the helper.

See
https://github.com/appwrite/templates/blob/main/ruby/starter/lib/main.rb

2023-10-20 05:51 UTC, afzal442 commented on ruby/meilisearch/lib/utils.rb
sorry @loks0n any chance?

2023-10-21 07:24 UTC, afzal442 commented on ruby/meilisearch/lib/utils.rb
cc @gewenyu99

2023-10-23 08:45 UTC, loks0n commented on ruby/meilisearch/lib/utils.rb
You can join our discord community and get help in our Hacktoberfest channel.

https://appwrite.io/discord

2023-10-23 08:47 UTC, loks0n requested changes
Please also provide a test video showing the function executing on Appwrite

2023-10-23 08:47 UTC, loks0n commented on ruby/sync_with_meilisearch/lib/utils.rb
Again, none of these functions are used...

Please change the behaviour of main.js to match that of the node function.

For example, throw_if_missing should be used at the start of the function execution to verify the function has the correct ENV variables set.

2023-10-29 05:48 UTC, afzal442 commented on ruby/sync_with_meilisearch/lib/main.rb
> +    context.response.set_body(html)
Hi @stnguyen90 Any review and suggestions will be review.

2023-10-29 05:50 UTC, afzal442 commented on ruby/sync_with_meilisearch/lib/main.rb
> +    context.response.set_body(html)
cc @loks0n

2023-10-30 09:39 UTC, loks0n requested changes
Please also provide a test video showing the function executing on Appwrite

2023-10-31 15:51 UTC, afzal442 commented
Sorry @loks0n I have been getting this below error. Yesterday, there were no issues, working fine. Any help?
```
Error 400
Execution error: Server Error

Type

general_argument_invalid
```

Otherwise, it's working fine.

2023-11-02 08:39 UTC, afzal442 commented
Hi @loks0n a test video added in the issue desc box. Plz review it.

2023-11-02 14:21 UTC, loks0n approved these changes

2023-11-02 14:21 UTC, merged

2024-04-07 14:10 UTC, afzal442 commented
my discord id is **afzal442**

cc @tessamero

2024-04-19 16:18 UTC, gewenyu99 commented
Thanks, be in touch soon!