Feat: Add Github Issue Bot Template for Node.js (TypeScript)
appwrite/templates pull request #243
Opened 2023-10-17 06:00 UTC by vimode

## What does this PR do?

Adds the Github Issue Bot Template for Node.js(Typescript).

## Test Plan

![200 OK](https://github.com/appwrite/templates/assets/39148877/fafd1b71-4f7d-46db-9831-08ce526401ba)
---
https://github.com/appwrite/templates/assets/39148877/482e6c56-3fb2-486a-96c6-862091b26abf

## Related PRs and Issues

Closes #147 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-10-19 14:44 UTC, Haimantika reviewed
LGTM

2023-10-23 08:19 UTC, loks0n approved these changes

2023-10-23 08:21 UTC, loks0n requested changes

2023-10-23 08:21 UTC, loks0n commented on node-typescript/github-issue-bot/src/utils.ts
> +
Can we remove the space and use the docstring comment format?
e.g.

/*
 * Blah bla blah ...
 */

2023-10-23 08:21 UTC, loks0n commented
Great PR! One small nitpick

2023-10-23 08:47 UTC, vimode commented
@loks0n Thank you. 

Updated the code comment as  per request.

2023-10-23 08:51 UTC, loks0n approved these changes
Amazing work! Merged

2023-10-23 08:51 UTC, merged

2024-04-08 20:16 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-10 13:32 UTC, vimode commented
Hey @gewenyu99 my discord is vimiaou :)

2024-04-19 16:14 UTC, gewenyu99 commented
Be in touch soon!