Feat implement whatsapp with vonage bun
appwrite/templates pull request #252
Opened 2023-10-31 15:09 UTC by parthj000

hey @Haimantika @loks0n , i have raised the PR please review it !!

This is a video demonstrating the bun whatsapp bot with vonagee-api

[](url)

https://github.com/appwrite/templates/assets/146522413/162ff112-5585-475c-b7d6-c0a725e21f19

2023-10-31 15:47 UTC, parthj000 commented
![image](https://github.com/appwrite/templates/assets/146522413/c653003d-f605-4a1a-a125-682d975bc2de)

2023-10-31 16:08 UTC, gewenyu99 requested changes
Hey, I see a few issues.
1. you've nested this under bun/starter, which is not entirely correct
2. You've created a standalone express server, this should be an [Appwrite Function](https://appwrite.io/docs/products/functions)

Thanks!

2023-10-31 16:08 UTC, gewenyu99 commented on bun/starter/whatsapp-with-vonage/README.md
> +## Run Locally
Please remove these additional sections and keep this consistent with the existing Whatsapp vonage templates

2023-10-31 16:08 UTC, gewenyu99 commented on bun/starter/whatsapp-with-vonage/src/main.js
> +import express from "express"
Why are you importing express? You don't need express with Appwrite functions, it's already got a node based webserver at the front

2023-10-31 22:01 UTC, parthj000 commented
@loks0n i have done all the required changes !!

2023-10-31 23:27 UTC, gewenyu99 commented
Hey,

Due to time constraints, I'm going to mark this PR `hacktoberfest-accepted` for now so you get DO's Hacktoberfest rewards. We'll continue to work with you on this issue for review and merge.

When it is merged, we'll contact you for Appwrite-specific Hacktoberfest swag.

Thanks for helping us improve Appwrite!

2023-11-01 10:12 UTC, loks0n requested changes

2023-11-01 10:12 UTC, loks0n commented on bun/starter/src/main.ts
> +    motto: "Build like a team of hundreds_",
Please revert this change.

2023-11-01 10:12 UTC, loks0n commented on bun/starter/package.json
Please revert this change.

2023-11-01 10:12 UTC, loks0n commented on bun/starter/bun.lockb
Please revert this change.

2023-11-01 10:12 UTC, loks0n commented on bun/starter/README.md
Please revert this change.

2023-11-01 10:12 UTC, loks0n commented on bun/starter/.gitignore
Please revert this change.

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +
Can you remove all the double empty lines in this file?

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +| Status  | showing the status of message    | body  | string| submitted/read/delievered          |
Please format the file with prettier

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +| Build Commands    | `Bun install src/main.js` |
This is not correct, please see the bun starter as an example

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +| Entrypoint        | `src/main.js`            |
This is not correct, please see the bun starter as an example

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +
We already mention this above, please remove this

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/public/index.html
Can you use the HTML from the `node/whatsapp-with-vonage` function and put it in `static` folder please

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +
There are loads of random empty lines in the this file... please remove them.

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +    const html = file("public/index.html")
This won't work, please check out how the other bun templates are doing it.

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +export default async ({ req, res, log, error }) => {
Try structuring the code in a similar way to the node template.

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +            await fetch("https://messages-sandbox.nexmo.com/v1/messages", requestOptions)
You need to import fetch from `undici`

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +        myHeaders.append("Accept", "application/json");
This header is not required

2023-11-01 10:12 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.js
> +        const raw = JSON.stringify({
raw is not a very descriptive name

2023-11-03 23:29 UTC, parthj000 commented
@loks0n , i have done the required changes !

2023-11-06 10:25 UTC, loks0n requested changes

2023-11-06 10:25 UTC, loks0n commented on bun/starter/README.md
> +  "motto": "Build like a team of hundreds_",
Please revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/starter/.gitignore
Revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/starter/README.md
> +No environment variables required.
Please revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/starter/package.json
> +}
Please revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/starter/bun.lockb
Please revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/starter/src/main.ts
> +import { Client } from "node-appwrite";
Please revert this change

2023-11-06 10:25 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +| Build Commands    | `Bun install ` |
Should be lowercase `bun install` here

2023-11-06 10:25 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  if (req.method === "POST") {
This if state is not required

2023-11-06 10:25 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +      await fetch(
Can we just do all this inline:
```js
  await fetch(`https://messages-sandbox.nexmo.com/v1/messages`, {
    method: 'POST',
    body: JSON.stringify({
      from: process.env.VONAGE_WHATSAPP_NUMBER,
      to: req.body.from,
      message_type: 'text',
      text: `Hi there! You sent me: ${req.body.text}`,
      channel: 'whatsapp',
    }),
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Basic ${basicAuthToken}`,
    },
  });
```

2023-11-06 10:25 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +    );
This is quite complicated. Take a look the [node template](https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L20)
```js
  const token = (req.headers.authorization ?? '').split(' ')[1];
  var decoded = jwt.verify(token, process.env.VONAGE_API_SIGNATURE_SECRET, {
    algorithms: ['HS256'],
  });

  if (sha256(req.bodyRaw) != decoded['payload_hash']) {
    return res.json({ ok: false, error: 'Payload hash mismatch.' }, 401);
  }
```

2023-11-07 00:28 UTC, parthj000 commented
@loks0n 
I m little confused which changes you want me to revert .
Besides it i have added payload hash verification , and also added the asked changes, can you review them !

2023-11-07 10:34 UTC, loks0n commented on bun/starter/README.md
> +No environment variables required.
Reset this file please, there is a whitespace change`git checkout origin/main bun/starter/README.md`

2023-11-07 10:37 UTC, loks0n requested changes

2023-11-07 10:37 UTC, loks0n commented on bun/starter/bun.lockb
Again reset this file

2023-11-07 10:37 UTC, loks0n commented on bun/starter/package.json
Reset this file please, there is a whitespace changegit checkout origin/main bun/starter/README.md

2023-11-07 10:37 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
We use a utils file for this is other templates, please look

2023-11-07 10:37 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
Please use the same flow as the existing node template. This is completely different

2023-11-07 10:37 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
Swap the case round and use early return here please https://refactoring.guru/replace-nested-conditional-with-guard-clauses

2023-11-07 10:38 UTC, loks0n commented
> @loks0n I m little confused which changes you want me to revert . Besides it i have added payload hash verification , and also added the asked changes, can you review them !

Please follow the Node template as closely as possible.

2023-11-08 14:52 UTC, loks0n requested changes
Hi, 

I'm spending a lot of time going back and forth with this PR - please try to address all my comments before resubmitting for review.

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  );
Formatting looks weird, please run prettier

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  const secret = `${Bun.env.VONAGE_API_KEY}:${Bun.env.VONAGE_ACCOUNT_SECRET}`;
This variable is unnecessary please match https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L35

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +    });
Why is it called `getStaticFiles` when it returns the contents of a single file?

Please make a function of format like `getStaticFile(filename: string)` as like https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L15

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +export default async ({ req, res, log, error }) => {
We need to throw if the environment variables are not set like here https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L7

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
This is very different to the node template, please match the node template as closely as possible but using Bun utilites.
https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L20

2023-11-08 14:52 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +export async function getStaticFiles() {
Please copy other bun templates to get the best version of this function

2023-11-10 15:41 UTC, loks0n requested changes

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +
Please change this comment to match the other TS templates https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/deno/whatsapp-with-vonage/src/utils.ts#L2

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +// Throws an error if any of the keys are missing from the object
https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/deno/whatsapp-with-vonage/src/utils.ts#L2

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +export default async ({ req, res, log, error }: any) => {
Can we add basic types here as shown here: https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/deno/whatsapp-with-vonage/src/main.ts#L6C1-L12C1

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +  "status": "delievered/submitted/read"
This is not what you actually return.

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
This is not necessary, please remove this

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  });
Please add a space before this section and use structure similar to here
https://github.com/appwrite/templates/blob/6dab35f1f221ba075640d93f5a8e374f4fba4349/node/whatsapp-with-vonage/src/main.js#L20

First assign `token` variable

Then assign `decoded` variable

2023-11-10 15:41 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +    return res.json({ ok: false, error: err.message }, 400);
This error is undocumented in the README

2023-11-12 09:13 UTC, parthj000 commented
@loks0n , but what will happen to the event webhook ,If I remove this then incoming event webhooks will not be addressed and in documentation it is written that the webhook must be responded with 2XX response and if not done the request will be retried ... so will it not cause any problem and is it efficient to not account the webhooks giving us the status of message ?
And I have removed "text" as a parameter from the throwIfMissing function .

Documentation -https://developer.vonage.com/en/api/messages-olympus#websockets

2023-11-14 11:28 UTC, parthj000 commented
Please review this ! @loks0n

2023-11-16 09:31 UTC, loks0n requested changes

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +```
Let's just remove this example to match the other readmes

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +## POST/
Please add a space between POST and /

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +## GET/
Please add a space between POST and /

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/README.md
> +```
Let's remove this section. We have already covered it.

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the newline here

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here and replace with a single newline

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here, and replace with a single new line

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here and replace with a single newline

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here and replace with a single newline

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here and replace with a single newline

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +
Please remove the double newline here and replace with a single newline

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +
Please remove the newline here

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/static/index.html
> +<!doctype html >
Please remove the space here <!doctype html >
```suggestion
<!doctype html>
```

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +  return html;
Let's remove the inline variable and just `return await Bun.file(filePath).text()`

2023-11-16 09:31 UTC, loks0n commented on bun/whatsapp-with-vonage/src/utils.ts
> +export async function getStaticFiles(fileName: string) {
Can we rename this `getStaticFile`

2023-11-16 13:28 UTC, parthj000 commented
updated !

2023-11-16 13:40 UTC, loks0n requested changes

2023-11-16 13:40 UTC, loks0n commented on bun/whatsapp-with-vonage/src/main.ts
> +  }
Please remove this.

2023-11-16 14:30 UTC, loks0n approved these changes

2023-11-16 14:32 UTC, merged

2024-04-08 20:14 UTC, gewenyu99 commented
Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship. 

Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-04-21 17:52 UTC, parthj000 commented
@gewenyu99 ,
pars0942

> Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship.
> 
> Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

2024-05-03 17:53 UTC, parthj000 commented
Hey , @gewenyu99,  I have not been contacted for the swags yet :)

2024-05-03 18:19 UTC, adityaoberai commented
> @gewenyu99 , pars0942
> 
> > Hey there! There were a lot of big PRs during this Hacktoberfest, and we wanted to give everyone ample time to collaborate with our engineering team. If you were able to merge your PRs during October, amazing. If it’s still not merged, don’t worry about it either. Either way, we’ve got your Hacktoberfest swag minted and ready to ship.
> > Please comment with your Discord username here so we can contact you about your shipping information to deliver your Hacktoberfest swag.

Hey Parth
Just sent you a friend request on DIscord. If you can accept it and DM me, I'll send over the form.