Add Together AI Demo
appwrite/templates pull request #280
Opened 2024-04-17 02:58 UTC by PineappleIOnic

## What does this PR do?

Adds a Together AI Template

## Test Plan

Tested it works on Appwrite Cloud

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-04-18 07:37 UTC, christyjacob4 commented on node/generate-with-together-ai/src/main.js
> +    'image': 'stabilityai/stable-diffusion-xl-base-1.0'
does the API only support text and images? The README.md says audio as well on Line 3 and 21

2024-04-18 10:27 UTC, christyjacob4 commented on node/generate-with-together-ai/static/index.html
> +  <title>Replicate Demo</title>
```suggestion
  <title>Together AI Demo</title>
```
Please run a search through the entire folder to make sure we dont make this mistake in other places

2024-04-18 10:27 UTC, christyjacob4 requested changes
Please address the comments

2024-04-24 04:41 UTC, PineappleIOnic commented
@christyjacob4 Resolved, ready for re-review

2024-05-02 05:48 UTC, christyjacob4 approved these changes

2024-05-02 05:48 UTC, merged